"""empty message

Revision ID: 02b825f522ff
Revises: 
Create Date: 2025-09-24 20:47:59.200472

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '02b825f522ff'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('baskets',
    sa.Column('title_books', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('author_books', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('item_count', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['author_books'], ['authors.id'], name=op.f('baskets_author_books_fkey')),
    sa.ForeignKeyConstraint(['title_books'], ['books.id'], name=op.f('baskets_title_books_fkey')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('baskets_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('baskets_pkey'))
    )
    op.create_table('users',
    sa.Column('email', sa.VARCHAR(length=40), autoincrement=False, nullable=True),
    sa.Column('passwords', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('date_reg', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('users_pkey'))
    )
    # ### end Alembic commands ###
