"""edit usermodel

Revision ID: 6e374c60a2cd
Revises: 6f5d8d3b9abd
Create Date: 2025-09-25 18:19:32.515821

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6e374c60a2cd'
down_revision: Union[str, Sequence[str], None] = '6f5d8d3b9abd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
