"""migration1

Revision ID: 824b77567c7f
Revises: 02b825f522ff
Create Date: 2025-09-24 21:10:00.211083

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '824b77567c7f'
down_revision: Union[str, Sequence[str], None] = '02b825f522ff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('genres', sa.Column('description', sa.String(length=30), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('genres', 'desctiption')
    # ### end Alembic commands ###
